stages:
  - build
  - linting and testing

build:
  stage: build
  image: node:18.16.0
  before_script:
    - npm install
  script:
    - npm run build


lint:
  stage: linting and testing
  image: trion/ng-cli:16.0.1
  script:
    - npm ci
    - npm run lint
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

test:
  stage: linting and testing
  image: trion/ng-cli-karma:16.0.1
  script:
    - npm ci
    - ng test --watch=false
