# .gitlab-ci.yml

stages:
  - build
  - test

lint:
  stage: build
  image: node:14
  before_script:
    - npm ci
  script:
    - npm run lint

test:
  stage: test
  image: node:14
  before_script:
    - npm ci
  script:
    - npm run test

build:
  stage: build
  image: node:14
  before_script:
    - npm ci
  script:
    - npm run build
